
CREATE TABLE MOLLYS_POTENTIAL_FOOD_TRAIN_BAIN_202008 AS(
WITH MOLLYS_RCIP_DETAIL_RECENT_BF6M AS (
     SELECT A.CUST_ID,A.AFLCO_CD,A.BIZTP_CD,B.GRADE_CD,A.BSN_DT,E.YM,A.PRDT_CD,C.PRDT_NM,D.PRDT_DCODE_CD,D.PRDT_DCODE_NM,C.PRDT_MCODE_CD,F.PRDT_MCODE_NM,C.PRDT_GCODE_CD,G.PRDT_GCODE_NM,D.PRDT_DI_CD,A.SALE_AMT,A.SALE_QTY,NULLIF(A.SALE_AMT,0)/NULLIF(A.SALE_QTY,0) AS QTY_SALE_AMT
	 FROM  CDS_DW.TB_DW_RCIPT_DETAIL A
	 LEFT JOIN ( SELECT CUST_ID,GRADE_CD
				 FROM CDS_DW.TB_BAIN_MEMBR_GRADE
				 WHERE GRADE_YM = '202008'
			   )                                   B ON A.CUST_ID = B.CUST_ID
	 LEFT JOIN( SELECT AFLCO_CD ,BIZTP_CD,PRDT_CD,PRDT_NM ,PRDT_DCODE_CD,PRDT_MCODE_CD,PRDT_GCODE_CD 
				FROM CDS_DW.TB_DW_PRDT_MASTR )     C ON A.PRDT_CD        = C.PRDT_CD              AND A.AFLCO_CD = C.AFLCO_CD AND A.BIZTP_CD = C.BIZTP_CD
	 LEFT JOIN( SELECT AFLCO_CD ,BIZTP_CD,PRDT_DCODE_CD,PRDT_DI_CD,PRDT_DCODE_NM
				FROM CDS_DW.TB_DW_PRDT_DCODE_CD)   D ON C.PRDT_DCODE_CD  = D.PRDT_DCODE_CD        AND D.AFLCO_CD = C.AFLCO_CD AND D.BIZTP_CD = C.BIZTP_CD
	 JOIN  CDS_DW.TB_DW_DT_MASTR                   E ON E.YMD  = A.BSN_DT 
	 LEFT JOIN (SELECT AFLCO_CD ,BIZTP_CD,PRDT_MCODE_CD,PRDT_MCODE_NM
				FROM CDS_DW.TB_DW_PRDT_MCODE_CD)   F ON F.PRDT_MCODE_CD  = C.PRDT_MCODE_CD        AND F.AFLCO_CD = C.AFLCO_CD AND F.BIZTP_CD = C.BIZTP_CD
	 LEFT JOIN (SELECT AFLCO_CD ,BIZTP_CD,PRDT_GCODE_CD,PRDT_GCODE_NM
				FROM CDS_DW.TB_DW_PRDT_GCODE_CD)   G ON G.PRDT_GCODE_CD  = C.PRDT_GCODE_CD        AND G.AFLCO_CD = C.AFLCO_CD AND G.BIZTP_CD = C.BIZTP_CD
		-- ★ 다른 기간으로 학습하고 싶을시 수정 필요 
	 WHERE A.BSN_DT BETWEEN TO_CHAR('20200301','YYYY-MM-DD') AND TO_CHAR('20200831','YYYY-MM-DD')
	   AND A.AFLCO_CD IN('001','007') 
	   AND A.BIZTP_CD IN('10' ,'00')
	   AND A.SALE_TRGT_YN    = 'Y'               
	   AND A.RL_SALE_TRGT_YN = 'Y'               
	   AND A.SALE_AMT > 0
	   AND A.CUST_ID IS NOT NULL
	   AND D.PRDT_DI_CD = 42
)
,MOLLYS_PRDT_AVG_SALES AS (
	SELECT A.PRDT_DCODE_CD
	      ,A.PRDT_DCODE_NM
	      ,ROUND(AVG(A.QTY_SALE_AMT),0)  AS AVG_SALE_AMT
	      ,COUNT(DISTINCT A.CUST_ID) AS PRDT_BUY_CUST_ID
	FROM   MOLLYS_RCIP_DETAIL_RECENT_BF6M A
	WHERE  A.PRDT_DI_CD = 42
	GROUP BY A.PRDT_DCODE_CD,A.PRDT_DCODE_NM
)
SELECT T1.* 
FROM(
	SELECT A.CUST_ID 
	       -- Target (Part1) 잠재 사료 고객 
	       ,MAX(CASE WHEN  A.PRDT_MCODE_CD IN('0075') THEN 1 ELSE 0 END )                                       AS DOG_FOOD_BUY_YN
	       ,MAX(CASE WHEN  A.PRDT_MCODE_CD IN('0276') THEN 1 ELSE 0 END )                                       AS CAT_FOOD_BUY_YN
	       -- 구매속성 변수 (공통) 
	       ,DAYS_BETWEEN(MAX(BSN_DT),TO_CHAR(ADD_MONTHS('202008',1),'YYYY-MM-DD'))                         		AS LAST_VISIT_DATE_DIFF     
	       ,MAX(C.RFM_LV_DI_MOLLYS)                                                                             AS RFM_LV_DI_MOLLYS
	       ,COALESCE(MAX(C.TOP1_STR_CD),0)                                                                      AS TOP1_STR_CD
	       ,COALESCE(MAX(C.TOP2_STR_CD),0)                                                                      AS TOP2_STR_CD
	       ,COUNT(DISTINCT BSN_DT)          																    AS TOT_FREQUENCY_CNT
	       ,COUNT(DISTINCT PRDT_CD)         																    AS BUY_PRDT_CD_CNT
	       ,COUNT(PRDT_CD)                  									                                AS TOT_RCIP_PRDT_CNT
	       ,SUM(CASE WHEN QTY_SALE_AMT > AVG_SALE_AMT THEN 1 ELSE 0 END)                                        AS TOT_PREMIUM_PRDT_CNT
	       ,COALESCE(ROUND((SUM(CASE WHEN QTY_SALE_AMT > AVG_SALE_AMT THEN 1 ELSE 0 END)/COUNT(PRDT_CD)),1),0)  AS PREMIUM_PRDT_CNT_RT
	       ,SUM(CASE WHEN A.PRDT_MCODE_CD NOT IN ('0075','0276') THEN SALE_AMT ELSE 0 END) 						        AS TOT_SALE_AMT
	       ,SUM(CASE WHEN A.PRDT_MCODE_CD NOT IN ('0075','0276') THEN SALE_QTY ELSE 0 END)                   		    AS TOT_SALE_QTY
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD NOT IN ('0075','0276') THEN PRDT_MCODE_CD ELSE NULL END)   		AS TOT_MCODE_CNT
	       
	      --0075 (2716-몰리스 펫페어) 
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_DCODE_CD IN ('2716') THEN BSN_DT ELSE NULL END) 							   		AS TOT_DCODE_2716_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_DCODE_CD IN ('2716') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_DCODE_2716_SALE_AMT
	       --0074	반려견간식
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0074') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_74_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_MCODE_CD IN ('0074') THEN SALE_AMT ELSE 0 END) 			             	                AS TOT_MCODE_74_SALE_AMT
	       --0076	패션용품
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0076') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_76_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_MCODE_CD IN ('0076') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_76_SALE_AMT
	       --0077	반려견일반용품
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0077') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_77_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_MCODE_CD IN ('0077') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_77_SALE_AMT
	       --0079	팝업스토어
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0079') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_79_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_MCODE_CD IN ('0079') THEN SALE_AMT ELSE 0 END) 					           			    AS TOT_MCODE_79_SALE_AMT
	       --0123	병원
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0123') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_123_FREQ_CNT
	       ,SUM( CASE WHEN A.PRDT_MCODE_CD IN ('0123') THEN SALE_AMT ELSE 0 END) 						       			    AS TOT_MCODE_123_SALE_AMT
	       --0124	미용
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0124') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_124_FREQ_CNT
	       ,SUM( CASE WHEN A.PRDT_MCODE_CD IN ('0124') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_124_SALE_AMT
	       --0125	데이케어
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0125') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_125_FREQ_CNT
	       ,SUM( CASE WHEN A.PRDT_MCODE_CD IN ('0125') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_125_SALE_AMT
	       --0126	분양
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0126') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_126_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_MCODE_CD IN ('0126') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_126_SALE_AMT
	       --0318   반려견위생용품
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0318') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_318_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_MCODE_CD IN ('0318') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_318_SALE_AMT
	       --0477	노브랜드 반려견식품
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0477') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_477_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_MCODE_CD IN ('0477') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_477_SALE_AMT
		   --0478	노브랜드 반려견용품
		   ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0478') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_478_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_MCODE_CD IN ('0478') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_478_SALE_AMT
	       -- CAT 
	       --0277	반려묘간식
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0277') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_277_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_MCODE_CD IN ('0277') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_277_SALE_AMT
	       --0279	노브랜드반려묘
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0279') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_279_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_MCODE_CD IN ('0279') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_279_SALE_AMT
	       --0280   반려묘놀이용품
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0280') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_280_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_DCODE_CD IN ('0280') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_280_SALE_AMT
	       --0281   반려묘생활용품
	       ,COUNT(DISTINCT CASE WHEN A.PRDT_MCODE_CD IN ('0281') THEN BSN_DT ELSE NULL END) 							   		AS TOT_MCODE_281_FREQ_CNT
	       ,SUM(  CASE WHEN A.PRDT_MCODE_CD IN ('0281') THEN SALE_AMT ELSE 0 END) 							   			    AS TOT_MCODE_281_SALE_AMT
	FROM MOLLYS_RCIP_DETAIL_RECENT_BF6M A
	LEFT JOIN MOLLYS_PRDT_AVG_SALES B ON A.PRDT_DCODE_CD = B.PRDT_DCODE_CD
	LEFT JOIN (SELECT * 
			   FROM CDS_AMT.TB_AMT_BIZTP_CUST_DNA_DATA 
			   WHERE YM_WCNT=TO_CHAR(ADD_MONTHS('202008',1),'YYYYMMDD')  AND AFLCO_CD ='001' AND BIZTP_CD ='10') C ON A.CUST_ID = C.CUST_ID 
	WHERE A.PRDT_DI_CD = 42
	GROUP BY A.CUST_ID 
) T1
-- 강아지,고양이 사료를 제외한 구매금액이 0인 (사료만 구매한 고객은 제외 : 사료와 타몰리스상품을 같이 구매한 고객들을 대상으로 삼기위함)
WHERE TOT_SALE_AMT > 0
)