WITH WEEKLY_MODULE_CD_COMB_TEST AS (
SELECT 'WEEKLY'AS BATCH_CYCLE,PRED_YMD,'TIMING'AS MODULE,'ALL_CUST_ID_CNT'  AS DNA_CD,COUNT(CASE WHEN CUST_ID IS NOT NULL THEN 1 ELSE NULL END)  AS DEC_VALUE FROM CDS_AMT.TB_AMT_TIMING_RESULT    GROUP BY PRED_YMD
UNION ALL SELECT 'WEEKLY'AS BATCH_CYCLE,PRED_YMD,'TIMING'AS MODULE,'PREDICT_CLASS'  AS DNA_CD,SUM(CASE WHEN PREDICT_CLASS IS NOT NULL THEN 1 ELSE 0 END)  AS DEC_VALUE FROM CDS_AMT.TB_AMT_TIMING_RESULT    GROUP BY PRED_YMD
UNION ALL SELECT 'WEEKLY'AS BATCH_CYCLE,PRED_YMD,'TIMING'AS MODULE,'EVENT_CLASS'  AS DNA_CD,SUM(CASE WHEN EVENT_CLASS IS NOT NULL THEN 1 ELSE 0 END)  AS DEC_VALUE FROM CDS_AMT.TB_AMT_TIMING_RESULT    GROUP BY PRED_YMD
UNION ALL SELECT 'WEEKLY'AS BATCH_CYCLE,PRED_YMD,'TIMING'AS MODULE,'C1_PROB'  AS DNA_CD,SUM(CASE WHEN C1_PROB IS NOT NULL THEN 1 ELSE 0 END)  AS DEC_VALUE FROM CDS_AMT.TB_AMT_TIMING_RESULT    GROUP BY PRED_YMD
UNION ALL SELECT 'WEEKLY'AS BATCH_CYCLE,PRED_YMD,'TIMING'AS MODULE,'C2_PROB'  AS DNA_CD,SUM(CASE WHEN C2_PROB IS NOT NULL THEN 1 ELSE 0 END)  AS DEC_VALUE FROM CDS_AMT.TB_AMT_TIMING_RESULT    GROUP BY PRED_YMD
UNION ALL SELECT 'WEEKLY'AS BATCH_CYCLE,PRED_YMD,'TIMING'AS MODULE,'C3_PROB'  AS DNA_CD,SUM(CASE WHEN C3_PROB IS NOT NULL THEN 1 ELSE 0 END)  AS DEC_VALUE FROM CDS_AMT.TB_AMT_TIMING_RESULT    GROUP BY PRED_YMD
UNION ALL SELECT 'WEEKLY'AS BATCH_CYCLE,PRED_YMD,'TIMING'AS MODULE,'C1_EVENT_SOFTMAX_PROB'  AS DNA_CD,SUM(CASE WHEN C1_EVENT_SOFTMAX_PROB IS NOT NULL THEN 1 ELSE 0 END)  AS DEC_VALUE FROM CDS_AMT.TB_AMT_TIMING_RESULT    GROUP BY PRED_YMD
UNION ALL SELECT 'WEEKLY'AS BATCH_CYCLE,PRED_YMD,'TIMING'AS MODULE,'C2_EVENT_SOFTMAX_PROB'  AS DNA_CD,SUM(CASE WHEN C2_EVENT_SOFTMAX_PROB IS NOT NULL THEN 1 ELSE 0 END)  AS DEC_VALUE FROM CDS_AMT.TB_AMT_TIMING_RESULT    GROUP BY PRED_YMD
UNION ALL SELECT 'WEEKLY'AS BATCH_CYCLE,PRED_YMD,'TIMING'AS MODULE,'C3_EVENT_SOFTMAX_PROB'  AS DNA_CD,SUM(CASE WHEN C3_EVENT_SOFTMAX_PROB IS NOT NULL THEN 1 ELSE 0 END)  AS DEC_VALUE FROM CDS_AMT.TB_AMT_TIMING_RESULT    GROUP BY PRED_YMD
)
SELECT *
FROM WEEKLY_MODULE_CD_COMB_TEST
WHERE 1=1
AND PRED_YMD IN ('20200901','20200908') -- 기준 일자입력
