-- 기준월 베인등급 08월 
CREATE TABLE TB_AMT_TIMING_TARGET_BAIN_202008 AS(
		SELECT T1.*,CASE WHEN DAYS_DIFF <= 7 THEN 1 
		                 WHEN DAYS_DIFF <= 21 THEN 2
		                 ELSE 3 
		                 END AS  CLASS_CAT
		FROM (
				SELECT A.CUST_ID
                                                       --■ 기준월 변경 
				      ,MAX(CASE WHEN B.BSN_DT BETWEEN TO_CHAR(ADD_DAYS('20200901',-31),'YYYYMMDD') AND TO_CHAR(ADD_DAYS('20200901', -1),'YYYYMMDD') THEN B.BSN_DT ELSE NULL END) AS PAST_MONTH_VISIT
				      ,MIN(CASE WHEN B.BSN_DT BETWEEN TO_CHAR(ADD_DAYS('20200901',0),'YYYYMMDD') AND TO_CHAR(ADD_DAYS('20200901', 29),'YYYYMMDD') THEN B.BSN_DT ELSE NULL END) AS TARGET_MONTH_VISIT
				      ,DAYS_BETWEEN(MAX(CASE WHEN B.BSN_DT BETWEEN TO_CHAR(ADD_DAYS('20200901',-31),'YYYYMMDD') AND TO_CHAR(ADD_DAYS('20200901', -1),'YYYYMMDD') THEN B.BSN_DT ELSE NULL END),
				                    MIN(CASE WHEN B.BSN_DT BETWEEN TO_CHAR(ADD_DAYS('20200901',0),'YYYYMMDD') AND TO_CHAR(ADD_DAYS('20200901', 29),'YYYYMMDD') THEN B.BSN_DT ELSE NULL END)) AS DAYS_DIFF
				FROM (SELECT DISTINCT  A.CUST_ID
						FROM  CDS_AMT.TB_AMT_BIZTP_CUST_DNA_DATA A 
						JOIN  CDS_DW.TB_BAIN_MEMBR_GRADE B ON A.CUST_ID  = B.CUST_ID AND B.GRADE_YM ='202008' 
						WHERE YM_WCNT ='20200901'
						  AND AFLCO_CD ='001'
						  AND BIZTP_CD ='10'
						  AND PURCHS_CYCLE IS NOT NULL) A
				LEFT JOIN (SELECT *
				      FROM CDS_DW.TB_DW_RCIPT_HDER 
				      WHERE AFLCO_CD = '001' 
				       AND BIZTP_CD = '10' 
				       AND TO_CHAR(BSN_DT,'YYYYMMDD') BETWEEN TO_CHAR(ADD_DAYS('20200901',-31),'YYYYMMDD') AND TO_CHAR(ADD_DAYS('20200901', 29),'YYYYMMDD')
				       AND SALE_SUM_AMT > 0
				      ) B ON A.CUST_ID = B.CUST_ID                              
				GROUP BY A.CUST_ID
		